### ISSUE TITLE
Pretrained checkpoints

### ISSUE THREAD

**Issue by GRAPH-0** [tencent-ailab/MDM#1]
Hi, thanks for this wonderful work! Would you like to release pre-trained checkpoints for QM9 and GeomDrug?

**Comment by GRAPH-0** [comment]
Hi guys，

I have tried running the code, but found it hard to reproduce the paper results. Some test results reported on QM9 are as follows:
![image](https://user-images.githubusercontent.com/85398576/231115891-6947e3eb-04f5-40fa-9cf7-bc01da823bc6.png)

Any suggestions for this?

BTW,  there are some minor bugs for training Geom Drug. Hope you can fix them in the future.

**Comment by Layne-Huang** [comment]
Hi,

Sorry for the late response. I have updated the test_eval.py script, which has some little errors.

You could run the command python test_eval.py --ckpt <checkpoint> --sampling_type generalized --w_global_pos 1 -- w_global_node 1 --w_local_pos 4 --w_local_node 5. Then you could overserve good performance of MDM.

Regarding the checkpoint, I will upload it later.

**Comment by GRAPH-0** [comment]
Got it!
Kind reminders about Geom Drug Training:
* soft_edges -> soft_edge https://github.com/tencent-ailab/MDM/blob/abdcd8b8e0ccd949946f3b010ede63c153f05351/configs/geom_full.yml#L18
* missing val_loader for Geom https://github.com/tencent-ailab/MDM/blob/abdcd8b8e0ccd949946f3b010ede63c153f05351/train.py#L213

**Comment by Layne-Huang** [comment]
> Got it! Kindly reminders about Geom Drug Training:
> 
> * soft_edges -> soft_edge https://github.com/tencent-ailab/MDM/blob/abdcd8b8e0ccd949946f3b010ede63c153f05351/configs/geom_full.yml#L18
> * missing val_loader for Geom https://github.com/tencent-ailab/MDM/blob/abdcd8b8e0ccd949946f3b010ede63c153f05351/train.py#L213

Thanks for your advice, they are very helpful. Actually, we did not utilize the validation dataset in the Geom-drugs dataset. You could split it by yourself.
