### ISSUE TITLE
error when running 'test_eval.py'

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [tencent-ailab/MDM#3]
Hi, thanks for your code, it's great : )
I got an error when running the test and eval command in README.md: `python test_eval.py --ckpt <checkpoint> --sampling_type generalized --w_global_pos 1 -- w_global_node 1 --w_local_pos 4 --w_local_node 5`.
the error is as follows:
_Traceback (most recent call last):
  File "/data/0shared/xxx/xxx/MDM/eval.py", line 69, in retrieve_qm9_smiles
    with open(file_name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../qm9/temp/qm9_smiles.pickle'_

Hope you'll help me with it, thanks a lot!!!

**Comment by Layne-Huang** [comment]
Hi,

Thank you for your interest.

You could run the `compute_qm9_smiles` function to obtain the desired file.

**Comment by jinzhuwei** [comment]
When run the compute_qm9_smiles function to obtain the desired file，the './data/GEOM/QM9/train_data_40k.pkl' folder was not found.
![image](https://github.com/tencent-ailab/MDM/assets/136072830/e475e63a-77ca-488f-b5ee-2ca3a0678b34)

**Comment by Layne-Huang** [comment]
> When run the compute_qm9_smiles function to obtain the desired file，the './data/GEOM/QM9/train_data_40k.pkl' folder was not found. ![image](https://user-images.githubusercontent.com/136072830/282367504-e475e63a-77ca-488f-b5ee-2ca3a0678b34.png)

You could use this link to get access to this data: https://portland-my.sharepoint.com/:u:/g/personal/lhuang93-c_my_cityu_edu_hk/EbpAY1autKdEggYTwGsf44MBtCIRunwncdWa4zUjOswmHQ?e=G8DEmR
