### ISSUE TITLE
Missing commands for conditional generation tasks

### ISSUE THREAD

**Issue by cl-github6** [tencent-ailab/MDM#4]
Hello, thank you for sharing your code. I encountered some issues while running it and would appreciate your assistance. I noticed that the provided code includes commands for running unconditional generation tasks but lacks commands for conditional generation. Could you please provide the corresponding commands for conditional generation to help us run the code more effectively? Thank you.

**Comment by Layne-Huang** [comment]
Hi,

Thanks for your interest. I have uploaded the conditional training script. Try it and generate the molecules with the desired properties!

**Comment by cl-github6** [comment]
> Hi,
> 
> Thanks for your interest. I have uploaded the conditional training script. Try it and generate the molecules with the desired properties!

Thank you very much and best wishes.
