### ISSUE TITLE
Code for evaluating conditional generation on QM9

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [tencent-ailab/MDM#6]
Dear author, I tried to run the code for evaluating **conditional generation** on QM9（eval_conditional_qm9.py）, but I found the code didn't work. Could you update the code please~
Best regards!

**Comment by Layne-Huang** [comment]
Hi,

Thanks for your interest. I have uploaded the scripts and updated the ReadMe.md. Please follow the instructions and generate the molecules with the desired properties.
