### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by AmingWu** [tencent-ailab/MDM#7]
Dear Authors,

When I run your code, there exists an error:

KeyError: 'positions is not a file in the archive'

**Comment by AmingWu** [comment]
![QQ截图20231230154322](https://github.com/tencent-ailab/MDM/assets/38445175/73bfe7b0-4ea5-4505-a53c-07ee872e2bf8)

**Comment by Layne-Huang** [comment]
Hi, 

Did you check your edge index? It seems like your edge index is None.

**Comment by AmingWu** [comment]
![QQ截图20240102091729](https://github.com/tencent-ailab/MDM/assets/38445175/32bfd25e-2052-4f3d-bbd1-f68a3e9a4662)
edge_index is not None

**Comment by AmingWu** [comment]
The type of size is NoneType

**Comment by Layne-Huang** [comment]
Maybe it is caused by your pyg version. The size is None by default.

**Comment by AmingWu** [comment]
The version of my torch_geometric is 2.4.0

**Comment by Layne-Huang** [comment]
Change the code to `size = self._check_input(edge_index, size)`. You also should update other similar functions.

**Comment by AmingWu** [comment]
Thank you. The code has been trained.

**Comment by AmingWu** [comment]
When I finished training, there exists an error of evaluation.
![捕获](https://github.com/tencent-ailab/MDM/assets/38445175/4e299356-7f74-43b0-99c7-9ca462c4f3a2)

**Comment by Layne-Huang** [comment]
If you train geom, you should comment the validation code or split the valid set by yourself.
